export enum Tipoconfiguracao {
  LED = 'LED',
  LED_RESTART = 'LED_RESTART',
  WIFI = 'WIFI',
  LORA_WAN = 'LORA_WAN',
  LORA_WAN_PARAM = 'LORA_WAN_PARAM',
  LORA_WAN_JOIN = 'LORA_WAN_JOIN',
  LORA_WAN_SEND = 'LORA_WAN_SEND',
  LORA_WAN_RESET = 'LORA_WAN_RESET',
  LIMPAR_FLASH = 'LIMPAR_FLASH',
  VIBRACAO = 'VIBRACAO'
}


