version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
